frontend/src/App.tsx
frontend/src/components/pages/HomePage.tsx
frontend/src/components/pages/IntakePage.tsx
frontend/src/components/pages/VisitPage.tsx
frontend/src/constants/Routes.ts

[Set up dummy homepage, /intake, /visit routes](https://www.notion.so/uwblueprintexecs/Set-up-dummy-homepage-intake-visit-routes-92313fb02a58421d8c5297f68fc2acca)
* Add dummy homepage, intake and visit routes
1. Navigate to `/`, `/intake`, `/visit`
2. Verify that the page changes
*  NOTE: These routes currently aren't protected (i.e. you don't need to be logged in to view it)! This will change later when we implement login/signup properly

Set up dummy homepage, /intake, /visit routes

---

backend/python/migrations/alembic.ini

Updated alembic.inic file to generate migration version file with a sequential naming.
[Update Alembic version naming convention](https://www.notion.so/uwblueprintexecs/Update-Alembic-version-naming-convention-8ca2f3719f284bc49443dbb16aa2971e)
* Changed the file_template variable in the file alembic.inic such that it creates migration file versions with this naming format - YYYYMMDD-description
1. Make changes to the schema and run migrations OR downgrade to base migration, then upgrade and finally generate a migration file
2. Verify that the migration file generated has naming of this format -> YYYYMMDD-description
* Does the migration file follow the specified format for it's naming?

Add date to migration file name

---

.github/workflows/heroku-deploy-dev-py.yml

[Configure GitHub actions Heroku deploy on merge to main](https://www.notion.so/uwblueprintexecs/Configure-GitHub-actions-Heroku-deploy-on-merge-to-main-c318c1a04b5c4b589762631a9f308c5b)
* added all secrets defined in github workflow file to the repository
* re-enable heroku deployments
1. Check that a heroku job was triggered for the `Test deployment` commit  ***NOTE: the job is only setup for running on `main` so it should fail on all PR branches
* I need to remove this flag so I can troubleshoot deploying on main (i.e. there may be more PRs related to enabling heroku deployments later)

Enable heroku deployments

---

backend/python/app/resources/access_type_dto.py
backend/python/app/services/implementations/access_type_service.py
backend/python/app/services/interfaces/access_type_service.py
backend/python/tests/unit/test_access_type_service.py

[Add new access types](https://www.notion.so/uwblueprintexecs/Add-new-access-types-64bbb4b9678c4ee3a6d3c8c86cb9c557)
* Created `get_access_type` and `add_new_access_type` methods in `AccessTypeService` file. `get_access_type` will call `add_new_access_type` is the access type does not already exist in the db, to create and return the DTO of the access type.
* Added unit tests
1. Run `docker exec -it cas_py_backend /bin/bash -c "pip install -e . && pytest"`
* Correct data validation is occurring in `CreateAccessTypeDTO`

Add New Access Type Service

---

backend/python/app/services/implementations/access_type_service.py
backend/python/app/services/interfaces/access_type_service.py
backend/python/tests/unit/test_access_type_service.py

[Get all access types](https://www.notion.so/uwblueprintexecs/Get-all-access-types-f59ba069dcc04109b18e84908133145b)
* Added `get_access_types` method to access type service files. Returns a list of `AccessTypeDTO` objects obtained by running `AccessType.query.all()`
* Log errors as strings
1. run `docker exec -it cas_py_backend /bin/bash -c "pip install -e . && pytest"`. Verify tests pass
* Verify that logging error as string is sufficient
* Test coverage

Implement Get All Access Types Method

---

backend/python/app/services/implementations/goal_service.py
backend/python/app/services/interfaces/goal_service.py
backend/python/tests/functional/test_goal_service.py

[Get goals given intake id](https://www.notion.so/uwblueprintexecs/Get-goals-given-intake-id-b4fc9040c686407ea0eef1f63b61e55f)
* In Goal service, query intake by ID, then return all goals associated with returned intake
1. Verify all python unit tests run accordingly
2.Verify migration applies with no errors by running docker exec -it cas_py_backend /bin/bash -c "flask db upgrade" and then docker exec -it cas_py_backend /bin/bash -c "flask db downgrade"
* Have to add more test cases. Once this is done, verify test coverage is complete

Add Query for Goals Given Intake ID

---

backend/python/app/middlewares/validate.py
backend/python/app/rest/__init__.py
backend/python/app/rest/caregiver_routes.py
backend/python/app/rest/user_routes.py
backend/python/app/services/implementations/caregiver_service.py
backend/python/app/services/implementations/user_service.py
backend/python/app/services/interfaces/caregiver_service.py
backend/python/tools/db_seed.py

[Implement POST /caregiver route](https://www.notion.so/uwblueprintexecs/Implement-POST-caregiver-route-7670810e31e64c22bf7a350f32cfe025)
* GET
* gets all caregivers
* if the caregiver table does not exist, returns `[]`
* POST
* adds a caregiver
* if the request is invalid (e.g. caretaker id already exists, foreign key not found, etc.), then do nothing
1. `docker-compose down --volumes` (after this, the `caregivers` relation does not exist)
2. `docker-compose up`
3. `curl -X GET http://localhost:5000/caregiver` (`[]` is the chosen response when `caregivers` does not exist)
4. `docker exec -it cas_py_backend /bin/bash -c "flask db upgrade"`
5. `docker exec -it cas_py_backend /bin/bash -c "python -m tools.db_seed"`
6. `curl -X GET http://localhost:5000/caregiver` (check that there are 2 …

[kai/caregiver-route] Add /caregiver route

---

frontend/src/components/intake/PromptBox.tsx
frontend/src/components/intake/child-information/ChildProviderForm.tsx

[Implement ‘Providers’ box within Add Child] (https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=fbcf786463c244adbcaf045b7ed8a41e&pm=s)
* Create DoublePromptBox to house two buttons instead of one
1. Go to http://localhost:3000/intake/add-child and check to make sure providers box is working
* providers box implementation

Implement ‘Providers’ box within Add Child

---

frontend/src/components/intake/IndividualDetailsEntry.tsx
frontend/src/components/intake/PromptBox.tsx
frontend/src/components/intake/child-information/ChildProviderForm.tsx

[Render Individual’s details through PromptBox](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=b4a8e66b22204b89a491ab4f47f839ae&pm=s)
* Add conditional rendering of individual information in PromptBox component
* Add unimplemented `Delete` and `View and edit details` buttons along with each generated piece of information
1. Go to any file which uses the PromptBox component (ie. `IndividualDetailsEntry.tsx`)
2. `import { IndividualDetailsOverview }`
3. Declare a test variable 
```
const testCaregivers: IndividualDetailsOverview[] = [
{firstName: "", secondName: "", fileNumber: ""},
{and so on},
]
```
4. Add the `individualDetails` prop with `testCaregivers` to the `PromptBox` of your choice
* Making sure information loads …

Render Individual’s details through PromptBox

---

frontend/src/components/intake/child-information/AddChildPage.tsx
frontend/src/components/intake/child-information/ChildInformationForm.tsx

[Add ‘Save Child Information’ button to Add Child flow](https://www.notion.so/uwblueprintexecs/Add-Save-Child-Information-button-to-Add-Child-flow-f6130403d9fe4e71ac2e490ba2ce40f1)
- Added footer to `AddChildPage.tsx` with save button since it makes more sense to have on save button instead of three (one on each form page). Also the Figma said "Primary button is disabled until all required fields across the three pages have valid inputs. "
- Added onKeyUp listeners to the Fields on the first form that update the state. This is useful for the future if format validation is implemented.
- Added check for required fields for the child Information. The other two forms are incomplete so did not add checks for that but left comments.
1. Open the form `http://localhost:3000/intake/add-child`
2. …

Add footer with save button to child form

---

frontend/src/components/intake/PermittedIndividualsModal.tsx
frontend/src/components/intake/ProgramForm.tsx

[Create Add ‘Other Permitted Individuals’ Modal](https://www.notion.so/uwblueprintexecs/Create-Add-Other-Permitted-Individuals-Modal-f7cbdc2f13d64a2289a62b91c814729e)
* Added UI for 'Other Permitted Individuals' modal under 'Program Details' page in intake
* No actual functionality, all it does is show the modal
* Modal does not appear on the 'Review Case Details' page
1. Go to /intake
2. Go to 'Program Details' tab in the stepper
3. At the bottom click the 'Add' button, modal should appear
* Make sure design is correct and buttons work

Create Add ‘Other Permitted Individuals’ Modal

---

frontend/src/components/intake/IndividualDetails.tsx
frontend/src/components/intake/ReviewCaseForm.tsx
frontend/src/components/pages/IntakePage.tsx

[Implement ‘Edit’ button function in Review Case page](https://www.notion.so/uwblueprintexecs/Implement-Edit-button-function-in-Review-Case-page-c0ccf94f1b8644448b168f33f0b038fb)
* Added functionality to 'Edit' buttons on Review Case page
* Allows user to go to back to specific sections to modify entries
* Removed 'Previous' button from Review Case page
1. Go to localhost:3000/intake
2. Fill in fields if you want and go to Review Case page
3. Click on 'Edit' buttons to make sure they return to the correct pages
4. Make sure the intake header changes depending on page (Initiate New Case vs Edit Case Intake Submission)
* Make sure 'Edit' buttons direct to correct pages
* Make sure header changes accordingly
* Check that 'Previous' button has been removed

Implement ‘Edit’ button function in Review Case page

---

frontend/src/components/intake/CourtInformationForm.tsx

[Implement “Download Attachment” button](https://www.notion.so/uwblueprintexecs/Implement-Download-Attachment-button-99d2ba30742c421b888c61a401ef4ad1?pvs=4)
* Implemented a button that downloads the orderreferral file object stored on upload 
1.http://localhost:3000/intake
* ensuring that the button is bug-free

Implement “Download Attachment” button

---

frontend/src/components/common/ModalComponent.tsx
frontend/src/components/intake/UnsavedProgressModal.tsx
frontend/src/components/intake/child-information/AddChildPage.tsx
frontend/src/components/pages/IntakePage.tsx

[Add return to dashboard & back to submission review functionality](https://www.notion.so/uwblueprintexecs/Add-return-to-dashboard-back-to-submission-review-functionality-df0828806f954a98be02a7534930cf6d)
* 'Back to dashboard / submission review' buttons and confirmation modals
1. Go to `/intake` and click the buttons on the initial intake page and also in edit submission mode
* Make sure the UI is correct and that the modal is correct in both versions

add return to dashboard & back to submission review functionality

---

frontend/src/App.tsx
frontend/src/components/intake/IndividualDetailsEntry.tsx
frontend/src/components/intake/child-information/AddChildPage.tsx
frontend/src/components/intake/intakeSteps.ts
frontend/src/components/pages/IntakePage.tsx
frontend/src/constants/Routes.ts

[Implement “Back to case individuals” button from Add Child](https://www.notion.so/uwblueprintexecs/Implement-Back-to-case-individuals-button-from-Add-Child-12e06f96d38147038aa36ccb2be64171)
* Removed `/intake/add-child` route and moved add child flow to the intake page
1. Type stuff into intake form
2. Go to 'Individual details' page and click 'Add child'
3. Click 'Back to case individuals' and make sure it redirects to'Individual details' page
4. Make sure the stuff you entered into the form earlier is still there
* Check that flow is correct

Implement “Back to case individuals” button from Add Child

---

backend/python/tools/db_wipe.py
frontend/src/components/pages/IntakePage.tsx

[Fix footer for smaller sized screens](https://www.notion.so/uwblueprintexecs/Fix-footer-for-smaller-sized-screens-4b7f3c7330df41ba9a7cf07051638457)
* Increase margin bottom on intake footer component
1. go to http://localhost:3000/intake to check out the new margin
* This is not a robust fix. If the footer height increases, then we might need to readjust the intake page bottom margins again.  (i.e. tight coupling between footer and intake page) A better solution would be to provide a ref of the wrapper html element to the footer component. The footer component's height would then we added on-top of the wrapper height. However, implementation details might get complex and I think a simple solution suffices for now (Since we don't worry too much about dynamic resizing).

Fix footer for smaller sized screens + Add database wipe script

---

frontend/src/components/intake/IndividualDetailsEntry.tsx
frontend/src/components/intake/child-information/AddChildPage.tsx
frontend/src/components/intake/child-information/ChildInformationForm.tsx
frontend/src/components/intake/child-information/SchoolDaycareForm.tsx
frontend/src/components/intake/indivDetails/CaregiverProviderForm.tsx
frontend/src/components/intake/indivDetails/ChildrenForm.tsx
frontend/src/components/pages/IntakePage.tsx

[Individual details section “view and edit details” button for children](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=85a193df9f5443718ca8383c0f1bcd45&pm=s)
* after adding child from `add child` page, children should be displayed in intake page on indiv details section
* should be able to delete children from indiv details section
* should be able to view and edit details from indiv details section
* prefill data for `child information`, `school/daycare`, and `providers`
1. go to `http://localhost:3000/intake`
2. add child
* check if persists + deletes properly
* click on view and edit details, check if info is prefilled

Individual details section “view and edit details” button for children

---

backend/python/app/rest/intake_routes.py
backend/python/app/services/implementations/intake_service.py
backend/python/app/services/interfaces/intake_service.py
backend/python/tests/functional/test_intake_service.py

[Main Dashboard GET Cases by Status with Pagination](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=d116ab525b8346759c7d8f7be420f02a&pm=s)
* paginate/filter GET response for `intake_service` 
* added `intake_status` query parameter
* added `page_number` and `page_limit` parameters for pagination by offset
1. run unit tests:
`docker exec -it cas_py_backend /bin/bash -c "pip install -e . && pytest"`
or run `intake_service` in postman: 
http://localhost:5000/intake?intake_status=ARCHIVED&page_number=1
* `get_all_intakes` in services/implementations/intake_service.py
* `get_all_intakes` in rest/intake_routes.py

Main Dashboard GET Cases by Status with Pagination

---

frontend/src/components/intake/IndividualDetails.tsx
frontend/src/components/intake/ReviewCaseForm.tsx
frontend/src/components/pages/IntakePage.tsx

[[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=a8943b2a8c3a4500bd948da5baae649e&pm=s)
* use data for individual details
1.
*

use children and caregivers information in review form

---

frontend/src/components/intake/indivDetails/CaregiverProviderForm.tsx

- Not a ticket, but noticed that after clicking `view and edit details` and trying to delete a caregiver, app crashes
- Had something todo with accessing an undefined caregiver based on the `selectedIndex` state
- Decided to reset the index each time caregiver is deleted, to avoid accessing undefined caregiver array indexes
1.
*

Fix edit caregiver to delete logic

---

backend/python/app/services/implementations/intake_service.py
backend/python/tools/db_seed.py
frontend/src/components/dashboard/CaseCard.tsx
frontend/src/components/pages/CaseOverview.tsx
frontend/src/constants/Routes.ts

[Refactor case overview routing to display proper case data](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=ec2d157a050d4c6b86a4da52a926f494&pm=s)
* Used useLocation(), & useParams() hook to implement dynamic routing for case overview and read case parameters ie. caseLead
1. Check that corresponding case number show up correctly when on case overview
2. Verify that dynamic route matches case number selected
3. Verify that correct caseLead is working
* Unsure about sustainability of pulling case data from useLocation hook instead of using intake service (GET request). No method currently exists for fetching data on singular case

Refactor case over routing to display proper case data

---

backend/python/app/rest/intake_routes.py
backend/python/app/services/implementations/child_behavior_service.py
backend/python/app/services/implementations/familial_concern_service.py
backend/python/app/services/interfaces/child_behavior_service.py
backend/python/app/services/interfaces/familial_concern_service.py
frontend/src/APIClients/IntakeAPIClient.ts

[Fill in Additional Fields and Restructuring Object for GET Intake ](https://www.notion.so/uwblueprintexecs/Fill-in-Additional-Fields-and-Restructuring-Object-for-GET-Intake-174d8c28af724a9b91fd3b5c6583b070?pvs=4)
* Added new methods in the familial concern service and child behavior service 
* Restructured GET intakes response with correct information including transport requirements, scheduling requirements, suggested start date, familial concerns,  concerns, and added the case referral and court information objects
1. Cards show up on the page 
2. Verify in postman that the response matches the desired response [here](https://www.notion.so/uwblueprintexecs/Intake-Frontend-Backend-b771b1d282974532b97e4d2d233e9144?pvs=4)
* The response from GET request (test in postman) 
* make sure UI …

Fill in Additional Fields and Restructuring Object for GET Intake 

---

frontend/src/components/dashboard/FilteredSection.tsx
frontend/src/components/pages/CasesPage.tsx
frontend/src/constants/Routes.ts

[Populate Dashboard with GET cases in View All section](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=fab314187b0c4d969172fcff45a7ac2e&pm=s)
Implement populating CasesPage.tsx with cases from backend through `get_all_cases` API
1. go to cases/<status> and view first 8 cases
2. press load more button at bottom
3. expected result: 8 more cases are shown
4. loadmore button will disappear when no more cases can be pulled
* once all cases have been loaded, loadmore button will no longer be shown

load cases in view all cases page

---

backend/python/testing.py

Summary of past 4 PRs:
- https://github.com/uwblueprint/childrens-aid-society/pull/231
- https://github.com/uwblueprint/childrens-aid-society/pull/230
- https://github.com/uwblueprint/childrens-aid-society/pull/229
- https://github.com/uwblueprint/childrens-aid-society/pull/228
1. Tried to login to heroku, couldn't; reset password, logged in again
2. Initial saw that Heroku was down for our backend—due to deprecated python version
3. Decided to bump versions (editing `runtime.txt` and editing `Dockerfile`), however, git could not recognize heroku credentials when merged
4. Realized that since I reset the password, the `HEROKU_API_KEY` var changed
5. Got a new api token, set the Github secrets var accordingly

Switching Python versions & Update HEROKU_API_KEY

---

backend/python/app/rest/visit.py
backend/python/app/services/implementations/attendance_sheet_service.py

* delete endpoint for visits (attendance sheets and records)
1. if deletion works
2. if deletion on invalid requests work
3. deletion on items not yet in the db are handled 
* as above 
- [ x] My PR name is descriptive and in imperative tense
- [ x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ x] I have run the appropriate linter(s)
- [x ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

visit-REST-delete endpoint new implementation
