uwblueprint/childrens-aid-society

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml, .github/workflows/heroku-deploy-dev-py.yml, .github/workflows/lint.yml
[Configure GitHub actions lint on merge/PR](https://www.notion.so/uwblueprintexecs/Configure-GitHub-actions-lint-on-merge-PR-dda79241da8244299d894ec9d27095c9)
* 
1.
*
=> Configure GitHub actions lint on merge/PR

README.md
[Add test running commands to README](https://www.notion.so/uwblueprintexecs/Add-test-running-commands-to-README-d450af2d759e43fb9583499b4145c2dd)
* 
1.
*
=> Add test command instructions to README

README.md, backend/python/app/resources/transportation_method_dto.py, backend/python/app/resources/user_dto.py, backend/python/app/services/implementations/intake_service.py, backend/python/app/services/interfaces/intake_service.py, backend/python/tests/functional/test_intake_service.py
[Add new transport methods](https://www.notion.so/uwblueprintexecs/Add-new-transport-methods-39b66c4cf04b4ceb853182f6825a49c7)
* Added function in `intake_service.py` to either retrieve the ID of an existing transport method / create a new one and return the ID
* Added tests to verify functionality
* Added `CreateTransportationMethodDTO` with basic validation for now
* ~~Pending merge of #15~~
1. Upgrade your database `docker exec -it cas_py_backend /bin/bash -c  "flask db upgrade"`
2. Run tests: `docker exec -it cas_py_backend /bin/bash -c "pip install -e . && pytest"` 
3. Verify that all of the tests pass
* Do the tests make sense?
* Does the implementation make sense? `implementations/intake_service.py`
=> Add new transportation methods

.github/workflows/codeql-analysis.yml, .github/workflows/codeql-config.yml
[Configure CodeQL Analysis](https://www.notion.so/uwblueprintexecs/Configure-CodeQL-Analysis-5da5720cfa664bf3a44d648ef6f05248)
* add github action to run codeql analysis on PRs/merges to main
* (ignore the messiness in the PR commit history oops)
1. Verify CI checks ran (ignore linting one, I didn't update any backend/frontend files so it shouldn't be triggered)
* Does it work?
=> Setup CodeQL Analysis

backend/python/app/services/implementations/transport_method_service.py, backend/python/tests/functional/test_transport_method_service.py
* broke some tests by renaming the file in another commit
1. Run `docker exec -it cas_py_backend /bin/bash -c "pip install -e . && 
pytest"` and check that the tests pass
* do the tests pass?
=> Fix import in transport method service

backend/python/app/resources/address_dto.py, backend/python/app/services/implementations/address_service.py, backend/python/app/services/interfaces/address_service.py, backend/python/tests/functional/test_address_service.py
[Create Service to add new address](https://www.notion.so/uwblueprintexecs/Create-service-to-add-new-address-350083b689fd47e6998d4b65d82d4786)
* Created class, and the associated method to allow creation of a new address record in the db when a CreateAddressDTO is passed to the method. AddressDTO is returned if the function is successful otherwise exception is raised.
* Added corresponding DTO classes with validation methods.
* Added tests to verify functionality
1) Upgrade your database docker exec -it cas_py_backend /bin/bash -c "flask db upgrade"
2) Run tests: docker exec -it cas_py_backend /bin/bash -c "pip install -e . && pytest"
3) Verify that all of the tests pass
* Do all the tests pass
=> Created services to allow creation of new address

backend/python/app/models/intake.py
* `familial_concerns` accidentally redeclared in intake model
1.
* note: no changes are needed to the migration for this
=> Fix duplicate familial_concerns in intake model

backend/python/app/services/implementations/transport_method_service.py, backend/python/app/services/interfaces/transport_method_service.py, backend/python/tests/functional/test_transport_method_service.py
[Get all transportation methods](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=dabf303df3f842889bfaa96c68ff1f0d)
* Modified transportation_method_service implementation and interface to add method get_transportation_methods
* Used TransportationMethod.query to get data and modified the data with to_dict() 
* Added error checking
* Added tests 
1. Run tests
2. Verify code changes in 3 files
* Run the tests. One test should fail (empty db) as I was not sure how to implement that test.
=> Add method get_all_transportation_methods

frontend/src/components/pages/IntakePage.tsx
[Setup basic Intake form flow](https://www.notion.so/uwblueprintexecs/Setup-basic-Intake-form-flow-f3209b882e834380a48120f11ffbb01b)
* Added prev step and next step functions into the IntakePage.jsx
* Added a switch statement to render different components
1. Run on local host and visit localhost:3000/intake and click the buttons to change the state and render differ components
* If rendering of different pages work
=> Setup Basic Intake Form Flow

backend/python/app/resources/concern_dto.py, backend/python/app/services/implementations/concern_service.py, backend/python/app/services/interfaces/concern_service.py, backend/python/tests/unit/test_concern_service.py
[Add New Familial / Child Concerns](https://www.notion.so/uwblueprintexecs/Add-new-familial-child-concerns-73f535b92ffd4d33be24e2c6d269acc5)
* Created familial/child concern functions with test
* Created ConcernDTO and test_concern_service.py
1. docker exec -it cas_py_backend /bin/bash -c "pip install -e . && pytest"
* If tests run successfully and it works
=> Add New Familial / Child Concerns

.github/workflows/lint.yml, frontend/src/APIClients/AuthAPIClient.ts, frontend/src/components/auth/Logout.tsx, frontend/src/components/auth/RefreshCredentials.tsx, frontend/src/components/crud/CreateForm.tsx, frontend/src/components/crud/DisplayTableContainer.tsx, frontend/src/components/crud/UpdateForm.tsx, frontend/src/components/pages/__tests__/Default.test.tsx
* Run `yarn fix` on existing frontend files
* Update GH actions node version 
1. Are any CI warnings raised?
* do things look right
=> Fix frontend lint GitHub action warnings

backend/python/app/resources/child_dto.py, backend/python/app/services/implementations/child_service.py, backend/python/app/services/interfaces/child_service.py, backend/python/tests/functional/test_child_service.py
[Add New Child](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=4b5e341502ee49778c36b198d9687a7e&pm=s)
* Modified interface and implemented add_new_child method 
* Wrote success and failure tests
* Modified Child-related DTOs and wrote validations
1. Run backend tests normally
* -
=> Added add_new_child

frontend/package.json, frontend/src/components/pages/HomePage.tsx, frontend/yarn.lock
[Set up icon library](https://www.notion.so/uwblueprintexecs/Set-up-icon-library-ff5f7c82f8134ac4a9c5adbd766ccfb4)
* Add `react-feather`
* Add sample usage of `Icon` to homepage
1. Navigate to homepage `/`
2. Check that icons render properly
* do icons look okay?
* does syntax for usage look okay?
=> Add feather-icons library

backend/python/app/services/implementations/concern_service.py, backend/python/app/services/interfaces/concern_service.py, backend/python/tests/functional/test_concern_service.py
[Get familial and child concerns](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
* made a query call based on the concern type that return a DTO for each entry in the result of the query
* added tests
1. start docker containers
2. ensure the cas_test database exists & db is up to date (flask db upgrade)
3. run `docker exec -it cas_py_backend /bin/bash -c "pip install -e . && pytest" `
* correct implementation
=> get all child and familial concerns

backend/python/app/resources/goal_dto.py, backend/python/app/services/implementations/goal_service.py, backend/python/app/services/interfaces/goal_service.py, backend/python/tests/functional/test_goal_service.py
[Add method to get and add a goal](https://www.notion.so/uwblueprintexecs/Add-method-to-get-and-add-a-goal-5c1d3c9da91743b99c580816d2cb96bc)
* followed along branches PR
=> Add method to get and add a goal

frontend/src/components/intake/IntakeHeader.tsx, frontend/src/components/pages/IntakePage.tsx
[Create intake form header component](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=723bcce645c94ce892e16f27a41264ce&pm=s)
* Added IntakeHeader component which has data passed down from props
* Specified appropriate types
* Used Chakra UI for design
1. Run the docker container and go to `localhost:3000/intake`
* Screenshot in Notion ticket
=> Add intake header component

frontend/src/components/pages/HomePage.tsx, frontend/src/theme/breakpoints.tsx, frontend/src/theme/index.tsx
[Setup Design System Breakpoints](https://www.notion.so/uwblueprintexecs/Set-up-design-system-breakpoints-fee035fda3bb4e1c8bccad2fcdc0fe11)
* Implemented Chakra UI custom theme for breakpoints
* Used the default sm, and large and modified the medium to be 54em
1. Run it locally on localhost:3000
2. using media queries/resize the width of your window to see if the box resizes it respectively to what is labelled
3. Test that when you make the window width size 54em/864pixels the box's width should change to 300/400
* Seeing if the media query works for the size
=> Set Up Design System Breakpoints

frontend/src/components/common/CustomTag.tsx, frontend/src/components/pages/HomePage.tsx, frontend/src/theme/containerStyles.tsx, frontend/src/theme/index.tsx, frontend/src/theme/tagStyles.tsx
[Setup Selection Item and Selection Item Container component styles](https://www.notion.so/uwblueprintexecs/Setup-Selection-Item-and-Selection-Item-Container-component-styles-7007fff03b7a4e39b3875b3cb37b7aab)
* Created a new custom tag with a custom theme for containers
* The custom tag is wrapped inside the container and changes colour based on state (Hover, Pressed)
1. Run it on localhost:3000 and see if it changes colour depending on hover, or clicked
* See if it matches the figma prototype/design indicated on the ticket
* If the tag component changes colour depending on the current state
=> Setup Selection Item And Selection Item Container Component Styles

backend/python/app/models/__init__.py, backend/python/app/models/other_permitted_individual.py
[Create Other Permitted Individuals](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
* created a new model for other permitted individuals
1. no way to test yet
* focus on whether the relationships are correct/typed well
=> create other permitted individuals

backend/python/app/resources/daytime_contact_dto.py, backend/python/app/resources/provider_dto.py, backend/python/app/services/implementations/provider_service.py, backend/python/app/services/interfaces/provider_service.py, backend/python/tests/functional/test_provider_service.py
[Create new provider](https://www.notion.so/uwblueprintexecs/Create-new-provider-f9ef8a5bf4b94fd9b17a85ca5d50f60f)
* Implemented by following the ticket description
1. Visually determine correctness of changes
2. ci/pytest are currently passing
* Everything has equal priority
=> [kai/provider-create-new] Add provider service and provider creation

backend/python/app/resources/caregiver_dto.py, backend/python/app/resources/child_dto.py, backend/python/app/resources/daytime_contact_dto.py
no ticket
* improve readability of some of our DTO files
1. Visual inspection
2. CI/Pytest are currently passing
* N/A
=> [kai/dto-readability] Improve DTO readability

backend/python/app/resources/intake_dto.py, backend/python/app/services/implementations/intake_service.py, backend/python/app/services/interfaces/intake_service.py, backend/python/tests/functional/test_intake_service.py
[Create new intake](https://www.notion.so/uwblueprintexecs/Create-new-intake-3228fac4fb224ed5a978f69c13c25763)
* Implemented by following the ticket description
1. Visually determine correctness of changes
2. ci/pytest are currently passing
* Everything has equal priority
=> [kai/intake-service-create] Add intake service creation

frontend/src/components/intake/ProgramForm.tsx, frontend/src/components/pages/IntakePage.tsx
https://www.notion.so/uwblueprintexecs/Implement-Program-Detail-page-form-fields-ef6a967755674cd5b94986f6f36b530a
[Implement Program Detail page form fields](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
* Added input types and fields to the Program Detail page form
1. [local](http://localhost:3000/intake)
* Making sure that the formatting and field types are correct
* Adding a list-selector element later on
=> Implement Program Detail page form fields

frontend/src/components/intake/child-information/AddChildPage.tsx, frontend/src/components/intake/child-information/SchoolDaycareForm.tsx
[Implement ‘School/Daycare’ page within Add Child](https://www.notion.so/uwblueprintexecs/Implement-School-Daycare-page-within-Add-Child-ddf67e01f44c4ebfb8284c56e35a6e58)
* Created the "School / Daycare" form in the "Add Child" page so it matches the spec in the hi-fi mockup.
1. Go to http://localhost:3000/intake/add-child
2. Click on the "School / Daycare" tab
* `AddChildPage.tsx` - added syntax changes
* `SchoolDaycareForm.tsx` - all the front end changes are here, implemented required features
=> Implement ‘School/Daycare’ page within Add Child

frontend/src/components/intake/CourtInformationForm.tsx, frontend/src/components/intake/ProgramForm.tsx, frontend/src/components/intake/ReferralForm.tsx, frontend/src/components/intake/ReviewCaseForm.tsx
quick bug fix, no ticket
Pass hideStepper and hideFooter to all relevant review case components
Reformat readOnly prop passing
1. go to review case form screen, should look normal
*
=> hide stepper in review form and reformat readonly props

frontend/src/components/intake/ProgramForm.tsx
very inconsequential and minor, just going to merge this
1.
*
=> fix: set program form footer current step

frontend/src/components/intake/IndividualDetailsEntry.tsx, frontend/src/components/intake/NewCaregiverModal.tsx, frontend/src/components/intake/NewProviderModal.tsx, frontend/src/components/intake/indivDetails/CaregiverProviderForm.tsx, frontend/src/components/pages/IntakePage.tsx
[Integrate Caregivers flow with add and delete functionality](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=1360e29be4534fcc96cf1e2482913211&pm=s)
* Implement "Add Caregiver" functionality
* Implement "Delete" functionality
1. Go to /intake/ and the Individual Details section
2. Try adding caretakers with the Add Caretaker button
3. Try deleting caretakers with the trash icon
* make sure logic works
=> Integrate Caregivers flow with add and delete functionality

backend/python/migrations/versions/2022-07-03_57f14d8ff8bf_condense_goals_and_concerns_models.py, backend/python/requirements.txt, backend/python/tests/functional/test_access_type_service.py, backend/python/tests/functional/test_branch_service.py
no ticket
* update linter requirements used in dockerfile to be up to date with workflow linter
* note that you should re-run `docker-compose up --build` to build your docker with the updated changes, before running the lint command `docker exec -it cas_py_backend /bin/bash -c "black . && isort --profile black ."`
1.
*
=> fix backend linter

frontend/package.json
no ticket
* resolve firebase hosting errors by adding openssl flag to build scripts
1.
*
=> fix firebase hosting

frontend/Dockerfile, frontend/package.json, frontend/src/components/common/CustomTag.tsx, frontend/src/components/intake/CourtInformationForm.tsx, frontend/src/components/intake/IndividualDetails.tsx, frontend/src/components/intake/IndividualDetailsEntry.tsx, frontend/src/components/intake/IntakeFormFooter.tsx, frontend/src/components/intake/ProgramForm.tsx, frontend/src/components/intake/ReferralForm.tsx, frontend/src/components/intake/ReviewCaseForm.tsx, frontend/src/components/intake/Stepper.tsx
no ticket
* minor changes, modified build script since Dockerfile was failing
1. run `docker-compose up --build` with the new script and everything should work fine
*
=> fix build script and minor style/lint issues

frontend/src/APIClients/IntakeAPIClient.ts
[Create Intake API client in frontend and GET route](https://www.notion.so/uwblueprintexecs/Create-Intake-API-client-in-frontend-and-GET-route-46cc216e529f4c139988cb6b69995522)
* Created Intake API client
* Implemented POST route for form data
1.
* Making sure that the route is set up properly
* testing to ensure that the API client is configured properly
* Token Authorization
=> Create Intake API client in frontend and POST route

frontend/src/components/common/ModalComponent.tsx, frontend/src/components/intake/DeleteConfirmationModal.tsx, frontend/src/components/intake/PermittedIndividualsForm.tsx, frontend/src/components/intake/PermittedIndividualsModal.tsx, frontend/src/components/intake/ProgramForm.tsx, frontend/src/components/intake/PromptBox.tsx, frontend/src/components/intake/ReviewCaseForm.tsx, frontend/src/components/pages/IntakePage.tsx
[Integrate Other Permitted Individuals add and delete](https://www.notion.so/uwblueprintexecs/Integrate-Other-Permitted-Individuals-add-and-delete-5d1197d13fa74173ae5bec614d217df3)
* Implemented add and delete for 'Other Permitted Individuals' section
* Added `DeleteConfirmationModal.tsx` which is a modal that asks the user if they're sure they wanna delete the item
* 'View and edit details' implementation is not completed - this is still WIP so I may do this is a separate PR
1. Go to `/intake` and go to 'Program Details' in the stepper
2. Click the 'Add' button at the bottom
3. Enter individual info and save it
4. Try adding more individuals and try deleting them too
* Check that you are able to add individuals
* Make sure the correct UI appears when the list of permitted individuals is …
=> implement 'Other Permitted Individuals' add and delete

frontend/src/components/intake/PermittedIndividualsForm.tsx, frontend/src/components/intake/PermittedIndividualsModal.tsx, frontend/src/components/intake/ProgramForm.tsx, frontend/src/components/intake/PromptBox.tsx, frontend/src/components/intake/ReviewCaseForm.tsx, frontend/src/components/pages/IntakePage.tsx
[Integrate Other Permitted Individuals add and delete](https://www.notion.so/uwblueprintexecs/Integrate-Other-Permitted-Individuals-add-and-delete-5d1197d13fa74173ae5bec614d217df3)
* 'View and edit details' button functionality
* Essentially just copied Eugene's PR #145
* Made `ProgramForm` and `PermittedIndividualsForm` separate components so it's easier to implement for the review page
1. Go to `/intake` and go to 'Program Details' in the stepper
2. Click the 'Add' button at the bottom
3. Enter individual info and save it
4. Test that editing the entries is working
* Make sure it works
* Make sure 'Case Review' page is also correct and no extra stuff is appearing
=> implement edit button for other permitted individuals

frontend/src/components/intake/CourtInformationForm.tsx, frontend/src/components/intake/IntakeFormFooter.tsx, frontend/src/components/intake/ProgramForm.tsx, frontend/src/components/intake/ReferralForm.tsx
[Add “Clear Page” button functionality](https://www.notion.so/uwblueprintexecs/Add-Clear-Page-button-functionality-9382685128fb4979b4f3b5d2a89b792a?pvs=4)
* Added clear button click functionality
* clears page on case referral
* clears page on court information and clears uploaded document
* clears page on program form page
1.http://localhost:3000/intake
* Ensure that clear page button works properly
=> Add “Clear Page” button functionality

frontend/src/components/intake/ExistingProviderModal.tsx, frontend/src/components/intake/child-information/AddChildPage.tsx, frontend/src/components/intake/child-information/ChildProviderForm.tsx, frontend/src/components/pages/IntakePage.tsx
[Implement Existing Provider selection](https://www.notion.so/uwblueprintexecs/Implement-Existing-Provider-selection-1bccdd5db12d483d8fcb0273c309ef12)
* Existing providers selection from the 'Add Child' flow
1. Run through the 'Add Child' flow
* Make sure things are added correctly
=> implement existing provider selection

frontend/src/App.tsx, frontend/src/components/auth/Logout.tsx, frontend/src/components/intake/IntakeHeader.tsx, frontend/src/components/pages/Default.tsx, frontend/src/components/pages/HomePage.tsx, frontend/src/components/pages/TemplatePage.tsx, frontend/src/constants/Routes.ts
…edit intake header
[Main Dashboard Page Frame](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=9ca1b900463b48b1b299a715ded4ff87&pm=s)
* Update Intake header to have an optional logout button display
* Move the template code into http://localhost:3000/template
* Create the hompage headers in http://localhost:3000/
1. Go to http://localhost:3000/template for visualization of header
* I'm not 100% sure that there is a reusable component already implemented for displaying a button with an icon next to it. Instead, I just implemented my own code (Exp:
```
<Button
height="100%"
px="2"
rounded="lg"
border="1px"
onClick={() => console.log("FINISH THIS CALLBACK")}
>
{" "}
<Center gridGap="1">
{" "}
<Icon as={FilePlus} />
<Spacer /> …
```
=> Main Dashboard Page Frame

frontend/src/components/intake/IndividualDetailsEntry.tsx, frontend/src/components/intake/child-information/AddChildPage.tsx, frontend/src/components/intake/child-information/SchoolDaycareForm.tsx, frontend/src/components/pages/IntakePage.tsx
[Integrate Add Child flow and child data saving](https://www.notion.so/uwblueprintexecs/Integrate-Add-Child-flow-and-child-data-saving-8bbfd18fd7674c7eb166076b4e88c8d9)
* Created `ChildrenDetails` type, stores child data
* Once user clicks on `Save Child Information`, `ChildrenDetails` gets updated
1. `console.log` spam
* Make sure `ChildrenDetails` gets updated
=> Integrate Add Child flow and child data saving

frontend/src/components/dashboard/PermanentDeleteModal.tsx, frontend/src/components/dashboard/StatusModal.tsx, frontend/src/components/pages/HomePage.tsx
no ticket
* refactored code a bit to combine #176  from Jackie with #173  from Kevin 
1. go to home page and see if the Test Status Button works
*
=> combine status and delete modal implementations

frontend/src/components/dashboard/CaseCard.tsx
[Main Dashboard Case Cards](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=819164235311446e843fa6b76fcb3b9b&pm=s)
* make a new component (in a new /component/dashboard folder) for this card so it can be reusable.
* export a new type for all the Case details, and this type should be passed as a prop into our new component.
* The View all icon does not perform an action for now.
1. pull branch and `import CaseCard from "../dashboard/CaseCard";` into `HomePage.tsx`
2. hardcode dummy card into homepage:
Pending case: 
`<CaseCard
caseTitle="Case 1"
caseLead="Case Lead"
date="28/05/2023"
familyName="family name"
caseTag="PENDING"
/>`
Active case: 
`<CaseCard
caseTitle="Case 1"
caseLead="Case Lead"
date="28/05/2023"
familyName="family …
=> Build Main Dashboard Case Card Component

frontend/src/components/auth/Logout.tsx, frontend/src/components/auth/LogoutModal.tsx, frontend/src/components/common/ModalComponent.tsx
[Implement Log Out Modal and Flow](https://www.notion.so/uwblueprintexecs/Implement-Log-Out-Modal-and-Flow-0119c7c9c45b4d57a82db4493d04b6fb?pvs=4)
* Added a Log out modal using `ModalComponent`
* Log out modal is controlled by the `Logout` button
* Moved to previous logout function to the confirmation button onClick in the modal
* Not exactly sure how to test that
1. Click logout button on the top right of the dashboard
2. See the Logout Modal that pops up
* Whether the logout function is correct
=> KevinC/ add logout modal

.github/workflows/heroku-deploy-dev-py.yml
=> update heroku app name deploy

backend/python/tools/db_seed.py, frontend/.prettierrc.js, frontend/src/APIClients/IntakeAPIClient.ts, frontend/src/App.tsx, frontend/src/components/dashboard/CaseCard.tsx, frontend/src/components/dashboard/FilteredSection.tsx, frontend/src/components/overview/CaseOverviewFooter.tsx, frontend/src/components/pages/CaseOverview.tsx, frontend/src/components/pages/HomePage.tsx, frontend/src/types/CaseStatus.ts, frontend/src/types/CasesContextTypes.ts
no ticket
integrating a lot of different tickets/components together
* active case card clicks into Case Overview
* visit cadence and archive case modals hooked up to Case Overview page
* update db seed with more cases
* revert IntakeAPIClient to previous commit from #198 , to map out entire intake response
* some refactoring of Case Status types 
1. the app should be more functional now and more flows are accessible
2. The preview link doesn't really work with the backend right now. You can pull the branch and then run docker commands (wipe docker/dbs, compose, upgrade, seed, etc.) to have the app get cases from the backend
*
=> integrate dashboard components and flows

frontend/src/components/pages/CaseOverview.tsx
[Case Overview Change Leads Component](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=eee12738f95549d0836ef9ecddec2923&pm=s)
* used intake route to change leads in case overview
* case overview not connected to specific intake yet so just using intake id = 1 for now
1.
*
=> Connect change leads with update route in intake

backend/python/tools/db_seed.py
* Fix seeding data into database 
1.
*
=> Add extra field in db_seed

backend/python/migrations/versions/2023-10-11_2e3a95429cdf_merging.py
=> Merge db heads

backend/python/app/rest/visit.py, backend/python/app/services/implementations/attendance_sheet_service.py, backend/python/app/services/interfaces/attendance_sheet_service.py, backend/python/app/services/interfaces/child_behavior_service.py
- Added some interface function method descriptions
- Fixed attendance sheet interface typos 
1.
*
=> Add interface descriptions & Fix Wordings

frontend/src/APIClients/IntakeAPIClient.ts, frontend/src/components/common/FilteredCaseDisplay.tsx, frontend/src/components/dashboard/CaseCard.tsx, frontend/src/components/dashboard/FilteredSection.tsx, frontend/src/components/pages/CaseOverview.tsx, frontend/src/components/pages/CasesPage.tsx, frontend/src/components/pages/HomePage.tsx
* Noticed we have a redundant `lead_access_worker` field on the frontend case dash, swapped any instances of lead with `referring_worker`
1.
*
=> Fix: Replace lead with referringWorker

heroku.txt
Heroku build is failing, here is the reason:
To solve: upgrade Python versions
ATTEMPT THREE
* 
1.
*
=> Testing again x2

backend/python/testing.py
Heroku build is failing, here is the reason:
To solve: upgrade Python versions
ATTEMPT FOUR
* 
1.
*
=> Testing x4

backend/python/app/resources/attendance_records_dto.py, backend/python/app/rest/visit.py, backend/python/migrations/versions/2023-12-12_5a6a8146dbb6_merging_two_heads.py, backend/python/tools/db_seed.py
- Small syntactical changes to visit.py—based on new attendance_record pr
* 
1.
*
=> Visit Route GET—Small changes

frontend/src/components/pages/VisitPage.tsx, frontend/src/components/visit/AttendanceForm.tsx, frontend/src/components/visit/ChildInfoForm.tsx, frontend/src/components/visit/SubmitVisitModal.tsx, frontend/src/components/visit/TransportationForm.tsx, frontend/src/components/visit/VisitFormFooter.tsx, frontend/src/components/visit/VisitTimestampForm.tsx, frontend/src/theme/buttonStyles.tsx
[Creating Visits Form](https://www.notion.so/uwblueprintexecs/134e1f159caa4f73939d11a700c325ad?v=39cf7d5a98384eb9af2bff2265d0ac8a&p=6ff6b600681043c28a66172362098d28&pm=s)
* Visit Form Skeleton with all required fields
* Addition of Attendance Form and Transportation form entries
* no state or value specific functions are implemented yet
* submit visit form modal 
1. preview link and go to visit page
2. try adding additional attendance and transportation entries
3. try removing attendance and transportation entries
4. if one entry is present, remove button should not show up
* I can start on working on the state aspect of it, idk if we're doing something similar to intake using context or if we're going the same method as caregiver modal state management. But this is what's done so far lol
=> Create Visit Form

backend/python/app/rest/auth_routes.py, frontend/src/components/intake/NewCaregiverModal.tsx
Add an additional logical && operator check for date
* 
1.
*
=> Small date fix in caregiver modal
